INSERT INTO USERS (USERNAME) VALUES ('CPU');
INSERT INTO USERS (USERNAME) VALUES ('ほんだ');
INSERT INTO USERS (USERNAME) VALUES ('いがき');

INSERT INTO MATCHINFO (USER1, USER2, USER1HAND, ISACTIVE) VALUES (1, 2, 'Gu', FALSE);
INSERT INTO MATCHINFO (USER1, USER2, USER1HAND, ISACTIVE) VALUES (2, 3, 'Choki', FALSE);

INSERT INTO MATCHES (USER1, USER2, USER1HAND, USER2HAND, ISACTIVE) VALUES (2, 1, 'Gu', 'Choki', FALSE);
INSERT INTO MATCHES (USER1, USER2, USER1HAND, USER2HAND, ISACTIVE) VALUES (2, 1, 'Gu', 'Gu', FALSE);
INSERT INTO MATCHES (USER1, USER2, USER1HAND, USER2HAND, ISACTIVE) VALUES (2, 1, 'Gu', 'Pa', FALSE);
