DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(20)
);

DROP TABLE IF EXISTS MATCHINFO;
CREATE TABLE MATCHINFO(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER1 BIGINT,
  USER2 BIGINT,
  USER1HAND VARCHAR(10),
  ISACTIVE BOOLEAN DEFAULT FALSE
);

DROP TABLE IF EXISTS MATCHES;
CREATE TABLE MATCHES(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER1 BIGINT,
  USER2 BIGINT,
  USER1HAND VARCHAR(10),
  USER2HAND VARCHAR(10),
  ISACTIVE BOOLEAN DEFAULT FALSE
);
